import type { SavingsOpportunity } from "../types.js";
import { generateTerraformPlan } from "../terraform/plan.js";

export interface PullRequestBundle {
  title: string;
  body: string;
  files: Array<{ path: string; content: string }>;
}

export function createPullRequestBundle(opportunities: SavingsOpportunity[]): PullRequestBundle {
  const plan = generateTerraformPlan(opportunities);
  const included = opportunities.filter(o => o.safety !== "DO_NOT_AUTOMATE");
  const total = included.reduce((sum, o) => sum + o.estimatedMonthlySavings, 0);
  const findings = opportunities.map(o =>
    "- **" + o.safety + "** `" + o.action + "` `" + o.resourceId + "` — " + o.reason + " — estimated " + o.estimatedMonthlySavings.toFixed(2) + "/month"
  );
  const body = [
    "## Cloud Autopilot change plan",
    "",
    "**This PR is a review artifact. Cloud Autopilot does not apply AWS mutations.**",
    "",
    "- Opportunities: " + included.length,
    "- Estimated monthly savings: " + total.toFixed(2),
    "- Generated: " + plan.generatedAt,
    "",
    "### Safety",
    "",
    "- `SAFE` items may be eligible for future automation after explicit policy approval.",
    "- `REVIEW` items require human approval.",
    "- `DO_NOT_AUTOMATE` items are excluded.",
    "",
    "### Findings",
    "",
    ...findings,
    "",
    "Generated by Cloud Autopilot.",
  ].join("\n");

  return {
    title: "cloud-autopilot: review " + included.length + " savings opportunit" + (included.length === 1 ? "y" : "ies"),
    body,
    files: plan.files,
  };
}